### ISSUE TITLE
Doubt about the solution

### ISSUE THREAD

**Issue by pookdeveloper** [iqbaldjulfri/lb4-jwt-role-based-auth-sample#5]
Hello where have you searched to get to this solution?

I do not understand how you have come to the conclusion of generating this part for example wrinting this class and methods:
````
this.bind(AuthenticationBindings.METADATA).toProvider(MyAuthMetadataProvider);
this.bind(MyAuthBindings.STRATEGY).toProvider(MyAuthStrategyProvider);
this.bind(AuthenticationBindings.AUTH_ACTION).toProvider(MyAuthActionProvider); 
````

I have searched in the looopback documentation but I do not see anything about generating an auth own

And in the: 
````
export class MyAuthMetadataProvider extends AuthMetadataProvider {
````

I can use :
````
value(): MyAuthMetadataProvider | 
````

I get this error:

![image](https://user-images.githubusercontent.com/3384734/58940338-82659a00-8779-11e9-921f-abe59cdfaa11.png)

I use typescript: "typescript": "~3.5.1"

Thankss!!! :)

**Comment by iqbaldjulfri** [comment]
1. You won't find it in the docs. You will have to read their code, and trace back how they implements the auth. Not everything is covered in the docs.
2. Check your package.json file and check the `@loopback/authentication` version. If yours is higher than mine, then the loopback team has updated it again. You should change it to mine or figure it out yourself what's wrong.

**Comment by pookdeveloper** [comment]
Thanks @iqbaldjulfri !

**Comment by iqbaldjulfri** [comment]
Do you know why that error you mention exists?

it's because `MyAuthMetadataProvider.value()` should return `MyAuthenticationMetadata | undefined` not `MyAuthMetadataProvider | undefined`.

https://github.com/iqbaldjulfri/lb4-jwt-role-based-auth-sample/blob/c004af75fa0b7150755f1098f0d9ce379e13fa16/src/auth.ts#L70
