### ISSUE TITLE
Support for @loopback/authentication v 3.0.0

### ISSUE THREAD

**Issue by GianlucaCesari** [iqbaldjulfri/lb4-jwt-role-based-auth-sample#9]
@loopback/authentication just realease v. 3.0.0, and it breaks a lot of things in this tutorial, any chance you're going to update it?

**Comment by bin4ryio** [comment]
Second this! Would appreciate if u can provide some pointer with the latest loopback.

**Comment by iqbaldjulfri** [comment]
branch master is now supporting v3.x

see #10 for changes
